[[headers]]
  for = "/Build/*.data.gz"
  [headers.values]
    Content-Encoding = "gzip"
    Content-Type = "application/octet-stream"
	
[[headers]]
  for = "/Build/*.wasm.gz"
  [headers.values]
    Content-Encoding = "gzip"
    Content-Type = "application/wasm"

[[headers]]                                                                      
  for = "/Build/*.js"                                                             
  [headers.values]
    Content-Encoding = "js"
    Content-Type = "application/javascript"
	
[[headers]]                                                                      
  for = "/Build/*.js.gz"                                                             
  [headers.values]
    Content-Encoding = "gzip"
    Content-Type = "application/javascript"