name: Label

on: [pull_request_target]

jobs:
  label:
    name: Set labels
    runs-on: ubuntu-latest
    steps:
      - name: Set labels
        uses: actions/labeler@main
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
