name: License

on: [workflow_dispatch]

jobs:
  license:
    name: Create and upload license
    runs-on: ubuntu-latest
    steps:
      - name: Create license
        id: createLicense
        uses: game-ci/unity-request-activation-file@v2

      - name: Upload license artifact
        uses: actions/upload-artifact@main
        with:
          name: ${{ steps.createLicense.outputs.filePath }}
          path: ${{ steps.createLicense.outputs.filePath }}
