name: Pipeline

on:
  push:
    branches-ignore:
      - 'production'
      - 'staging'
      # TODO: remove
      - 'master'
      - chore/#185161544-ci-cd-continued

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yml
    secrets: inherit

  buildWebGL:
    name: Build WebGL
    needs: [test]
    uses: ./.github/workflows/build-webgl.yml
    secrets: inherit
